baseURL: https://raph.8el.eu
params:
  description: 'just a random site on the interweb' 
  author: raphael   
  github: https://github.com/raphjaph
  email: raphjaph@protonmail.com
  telegram: https://t.me/raphjaph
